# Don't run that if you want to start All Service.

version: '3.8'

services:
  db:
    image: postgres:16.2-alpine 
    restart: always
    environment:
      POSTGRES_DB: fastapi_db 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: mysecretpassword 
    ports:
      - "5432:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fastapi_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data: 
  prometheus_data: